### ISSUE TITLE
Clean up the documentation

### ISSUE THREAD

**Issue by antoyo** [gtk-rs/lgpl-docs#26]
Hello.
I can see 404 errors on the documentation website.
For intsance, when I search for `TreeView` and click on `gtk::TreeViewExt`, I get to [this page](http://gtk-rs.org/docs/gtk/trait.TreeViewExt.html) which is not found.
I think you need to clean up the documentation (delete, then re-generate) to fix this issue.
Thanks.

**Comment by GuillaumeGomez** [comment]
A few things need to be improved in the way we generate docs. I think we'll generate each crate on its own and then link them by hand. I'll check how to do so later on.

**Comment by EPashkin** [comment]
@antoyo Seems all good now.

**Comment by antoyo** [comment]
Thank you.
